version: 2
updates:

   # Maintain npm dependencies for KueueViz frontend
  - package-ecosystem: "npm"
    directory: "/cmd/kueueviz/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
    groups:
      all:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@mui/*"

  # Update block specifically for @mui/* packages
  - package-ecosystem: "npm"
    directory: "/cmd/kueueviz/frontend"
    schedule:
      interval: "weekly"
    groups:
      mui-packages:
        patterns:
          - "@mui/*"
    commit-message:
      message: "Bump mui packages from {{before}} to {{after}}"
