version: 2
updates:
   # Maintain shellcheck dependency
  - package-ecosystem: "docker"
    directory: "/hack/shellcheck"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"

