name: Merge main into website
description: Merge the main branch into the website branch.

outputs:
  message:
    description: Detail message about the outcome
    value: ${{ steps.merge-main-into-website.outputs.message }}

runs:
  using: composite
  steps:
    - name: Merge main into website
      id: merge-main-into-website
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "message=✅ Merged the main branch into the website branch." >> "$GITHUB_OUTPUT"
