on:
  release:
    types: [released]
jobs:
  krew-release:
    if: ${{ github.repository == 'kubernetes-sigs/kueue' && !github.event.release.prerelease }}
    runs-on: ubuntu-24.04
    steps:
      - name: Update new version in krew-index
        uses: ./.github/actions/krew-release
        with:
          version: ${{ github.ref_name }}
