name: Test PR Trigger
on:
  pull_request:
    types: [closed]
permissions:
  pull-requests: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR #${{ github.event.pull_request.number }} triggered at $(date)"